# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180306_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(choices=[('true', '在线'), ('false', '离线')], default='True'),
        ),
    ]
