# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180313_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='image/user/default', upload_to='static/media/user/%Y%m'),
        ),
    ]
