# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180313_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
    ]
