# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
