# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180314_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='', max_length=10, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='详细地址'),
        ),
    ]
