# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-31 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180324_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.IntegerField(verbose_name='发送对象')),
                ('message', models.TextField(verbose_name='信息内容')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='方送时间')),
            ],
            options={
                'verbose_name_plural': '消息',
                'verbose_name': '消息',
            },
        ),
    ]
