# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-31 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
    ]
