# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180320_1653'),
        ('business', '0003_auto_20180320_1645'),
        ('Ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0, verbose_name='总价')),
                ('status', models.CharField(choices=[('1', '已提交'), ('2', '已接单'), ('3', '配送中'), ('4', '已完成')], default='1', max_length=20)),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('discount', models.FloatField(default=0.0, verbose_name='折扣')),
                ('address', models.CharField(default='', max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='count',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='price',
        ),
    ]
