# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0002_auto_20180322_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='total',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ordering.Ordering', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='discount',
            field=models.FloatField(default=1.0, verbose_name='折扣'),
        ),
    ]
