# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0003_auto_20180322_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
