# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0004_ordering_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
        migrations.AddField(
            model_name='ordering',
            name='total',
            field=models.FloatField(default=0.0, verbose_name='总价'),
        ),
    ]
