# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0008_auto_20180326_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
