# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0009_orderdetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='business',
        ),
        migrations.AddField(
            model_name='ordering',
            name='bimage',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='ordering',
            name='bname',
            field=models.CharField(default='', max_length=50, verbose_name='商家名称'),
        ),
    ]
