# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0010_auto_20180326_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='bid',
            field=models.IntegerField(default=0, verbose_name='商家ID'),
        ),
    ]
