# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0011_ordering_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='status',
            field=models.CharField(choices=[('1', '已付款'), ('2', '已接单'), ('3', '配送中'), ('4', '已完成'), ('5', '未付款')], default='5', max_length=30),
        ),
    ]
