# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='business',
            name='baddress',
            field=models.CharField(max_length=300, verbose_name='详细地址'),
        ),
    ]
