# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180320_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hit_nums',
            field=models.IntegerField(default=0, verbose_name='点餐人数'),
        ),
    ]
