# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_hit_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
    ]
