# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_fav_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bstatus',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
