# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20180327_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='baddress',
            field=models.CharField(default='', max_length=300, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='business',
            name='bname',
            field=models.CharField(default='默认名称', max_length=300, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='business',
            name='bphone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
