# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-31 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='BusinessMessage',
        ),
    ]
