# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-06 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('mprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
                ('mimage', models.ImageField(upload_to='image/menu/%Y%m', verbose_name='菜品封面')),
                ('discout', models.FloatField(default=0.0, verbose_name='折扣')),
                ('people_num', models.IntegerField(default=0, verbose_name='点餐人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
            options={
                'verbose_name_plural': '菜品信息',
                'verbose_name': '菜品信息',
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='菜品类型')),
                ('mbusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.MenuInfo')),
            ],
        ),
    ]
