# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-06 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name': '菜品类型', 'verbose_name_plural': '菜品类型'},
        ),
        migrations.RemoveField(
            model_name='menutype',
            name='mbusiness',
        ),
        migrations.RemoveField(
            model_name='menutype',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuinfo',
            name='menu_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Menu.MenuType'),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
