# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-07 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20180306_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuinfo',
            old_name='discout',
            new_name='discount',
        ),
    ]
