# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20180307_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家名称'),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='discount',
            field=models.FloatField(verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='menu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.MenuType', verbose_name='菜品类型'),
        ),
    ]
