# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_auto_20180312_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='discount',
            field=models.FloatField(default=1.0, verbose_name='折扣'),
        ),
    ]
