# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_auto_20180322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='mprice',
            field=models.FloatField(default=0.0, verbose_name='单价'),
        ),
    ]
